apiVersion: skaffold/v4beta3
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false

  artifacts:
    - image: udemyclone/user
      context: services/user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: udemyclone/auth
      context: services/auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: udemyclone/category
      context: services/category-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: udemyclone/course
      context: services/course-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .