apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: udemyclone/user
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "user-db-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "udemy-user_service_dev"
            - name: NODE_ENV
              value: "development"
            - name: REDIS_HOST
              value: "user-redis-srv"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_EXPIRE
              value: "36000s"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
          envFrom:
            - secretRef:
                name: user-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
